---
title: "p8105_hw5_yw3438"
author: "Yuning Wang"
date: "10/31/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rvest)
library(purrr)
library(viridis)
```

## Problem 1

```{r}
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species)) %>% 
  janitor::clean_names()
```



```{r}
replace_measure = function(x) {
  
  if (is.numeric(x)) {
    replace(x, is.na(x), mean(x, na.rm = TRUE))
  } else if (is.character(x)) {
    replace(x, is.na(x), "virginica")
  }
  
}


output = map(iris_with_missing, replace_measure)
output

```



## Problem 2

```{r message=FALSE, warning=FALSE}
# Read in and tidy the filenames into a dataframe
files_name = data.frame(list.files("./data")) 
colnames(files_name) = "file_name"

# Write a function to read in the data of all the files
read_data = function(x) {
  
  read_csv(paste0("./data/", x)) 
  
}

# Save the results in a column in the dataset
file_datas = files_name %>% 
  mutate(data = purrr::map(files_name$file_name, read_data)) %>% 
  unnest()

# Tidy the data
file_data_tidy = file_datas %>% 
  pivot_longer(
    week_1:week_8,
    names_to = "week",
    values_to = "data"
  ) %>% 
  mutate(file_name = str_remove(file_name, ".csv"),
         week = str_remove(week, "week_")) %>% 
  separate(file_name, c("group", "subject_id"), sep = "_") %>% 
  mutate(group = recode(group, "con" = "control", 
                        "exp" = "experimental"))

# Draw a lineplot that reflect
file_data_tidy %>% 
  ggplot(aes(x = week, y = data, 
             color = subject_id, group = subject_id)) + 
  geom_point(alpha = .5) + 
  geom_line() +
  theme_bw() +
  theme(legend.position = "bottom") +
  labs(
    x = "Week",
    y = "Data Value",
    title = "Observations on Each Subject Over Time"
  ) +
  viridis::scale_color_viridis(
    name = "Subject ID", 
    discrete = TRUE
  ) +
  facet_grid(~group)
```







